version: '3.8'

services:
  db:
    image: postgres:13
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: transcendence
      POSTGRES_USER: osparolos
      POSTGRES_PASSWORD: coxinha123
    networks:
      - transcendence-network

  backend:
    build: ./backend
    container_name: backend
    networks:
      - transcendence-network
    depends_on:
      - db

    environment:
      VAULT_ADDR: http://vault:8201
      VAULT_TOKEN_FILE: /code/root_token.txt
    volumes:
      - ./backend:/code
      - shared-data:/vault/token/
    restart: on-failure


networks:
  transcendence-network:
    name: transcendence-network
    driver: bridge

volumes:
  postgres_data:
  shared-data:
    driver: local