version: '3.8'

services:
  db:
    image: postgres:13
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: transcendence
      POSTGRES_USER: osparolos
      POSTGRES_PASSWORD: coxinha123
    networks:
      - transcendence-network

  backend:
    build: ./backend
    container_name: backend
    networks:
      - transcendence-network
    depends_on:
      - db
      - vault
    environment:
      VAULT_ADDR: http://vault:8201
      VAULT_TOKEN_FILE: /vault/token/root_token.txt

    volumes:
      - ./backend:/code
      - shared-data:/vault/token/
    restart: on-failure
  
  pong:
    build: ./game
    container_name: pong
    networks:
      - transcendence-network
    depends_on:
      - backend
      - db
      - reverse-proxy
    ports:
      - 8080:80
    restart: on-failure

  reverse-proxy:
    build: ./reverse_proxy
    container_name: reverse-proxy
    networks:
      - transcendence-network
    depends_on:
      - backend
      - vault
    ports:
      - "443:443"

  vault:
    build: ./vault
    container_name: vault
    cap_add:
      - IPC_LOCK
    networks:
      transcendence-network:
        aliases:
          - vault
    volumes:
      - shared-data:/vault/token/
    env_file:
      - ./vault/.env
    environment:
      VAULT_ADDR: http://localhost:8200

networks:
  transcendence-network:
    name: transcendence-network
    driver: bridge

volumes:
  postgres_data:
  shared-data:
    driver: local